server:
  port: 9090


spring:
  application:
    name: personal-bot-hub
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${POSTGRES_JDBC_URL}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    hikari:
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    show-sql: true

  liquibase:
    enabled: false
    #default-schema: ${POSTGRES_SCHEMA:pins}
    #change-log: db/changelog/db.changelog-master.yaml
    #change-log: classpath:/${POSTGRES_SCHEMA:pins}/master.yml
  devtools:
    restart:
      exclude: "**/static/**"
      additional-paths: "src/main/resources"
jwt:
  key:
    filename:
      private: jwt/private_key
      public: jwt/public_key

telegram:
  bot:
    token: ${TELEGRAM_BOT_TOKEN}
    name: bothub


logging:
  level:
    com.pengrad.telegrambot: DEBUG